<form action="<?=  $block->getFormAction(); ?>" method="post">

	<?php echo $this->getBlockHtml('formkey') ?>
  <div class="form-group">
    <label for="name">Select the category :</label> <br>
    
    <?php 



    $categories = $block->getCategoryCollection();

   // var_dump($categories);
      ?>
    <select class="form-control" id="cat_id" name="cat_id" style="width:400px;height: 34px" required>
      <option value=''>None</option>
         <?php foreach ($categories as $category) {
   echo $category->getData('discount_amount');
   // die('die');
    $discount=$block->getDiscountbyCategory($category->getId());
    if($discount){
      echo '<option value="'.$category->getId().'">'.$category->getName() .' --------- Discount: '.$discount. '%</option>';
    }else{
          echo '<option value="'.$category->getId().'">'.$category->getName().'</option>';
    }

}

?>
    </select> <br> <br>
</div>

<h3> OR </h3>

<div class="form-group">
<label for="category_id">Place the category id (make sure you selected none in the above field) </label> <br>
<input type="text" name="category_id" id="category_id" class="form-control" style="padding:5px 7px;width:400px;height: 34px"  /> <br>
</div>  <br>




<div class="form-group">
	<label for="price_action"> Choose Action : </label> <br>
<!-- <div class="radio">
  <label><input type="radio" name="price_action" value="1" >Increase Product Price (Manual price) </label> <br>
</div>

<div class="radio">
  <label><input type="radio" name="price_action" value="3" >Decrease Product price (Manual Price: apply only for the prices increased using the first action) </label> <br>
</div> -->


<div class="radio">
  <label><input type="radio" name="price_action" value="0" required>Apply Discount    </label> <br>
</div>

<div class="radio">
  <label><input type="radio" name="price_action" value="2"  required>Remove Discount  </label> <br>
</div>

</div> <br>

<div class="form-group">
<label for="update_amount">write the amount in percentage (%) </label> <br>
<input type="number" name="update_amount" step="1" min="0" max="100" class="form-control" style="padding:5px 7px;width:400px;height: 34px" required /> <br>
</div>	<br>



<div class="form-group">
	
    <input type="submit" class="btn btn-primary" value="Apply !" /> <input type="reset" value="Reset "/ > <br>
  </div>
</form>

<script type="text/javascript">
    require(['jquery','jquery/ui'],function($){

  $('#category_id').change(function(){
  if($(this).val()!=''){
  $('#cat_id').removeAttr('required');
  }

  });

  $("input[name=price_action]").change(function(){
  //alert($("input[name=price_action]:checked").val());
     if($("input[name=price_action]:checked").val()==2){
 $("input[name=update_amount]").removeAttr('required');
  $("input[name=update_amount]").val('');
   $("input[name=update_amount]").prop('disabled',true);

  }else{
    $("input[name=update_amount]").attr('required',true);
    $("input[name=update_amount]").prop('disabled',false);
  }
  });

  
  });

</script>
